/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.shader {
    export class MeltEffectUI extends Scene {
		public img:Laya.Image;
		public slider:Laya.HSlider;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("shader/MeltEffect");
        }
    }
    REG("ui.shader.MeltEffectUI",MeltEffectUI);
}