/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import MeltEffectSceneCtrl from "./shader/MeltEffectSceneCtrl"
import ShaderDissolve from "./shader/ShaderDissolve"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1624;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="shader/MeltEffect.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=true;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("shader/MeltEffectSceneCtrl.ts",MeltEffectSceneCtrl);
        reg("shader/ShaderDissolve.ts",ShaderDissolve);
    }
}
GameConfig.init();